#!/usr/bin/env bash

if
  [[ -s "/home/amunene/Development/Phase3/phase-3-orms-mapping-classes-to-database-tables/HOME/.gem/environment" ]]
then
  source "/home/amunene/Development/Phase3/phase-3-orms-mapping-classes-to-database-tables/HOME/.gem/environment"
  exec racc "$@"
else
  echo "ERROR: Missing RVM environment file: '/home/amunene/Development/Phase3/phase-3-orms-mapping-classes-to-database-tables/HOME/.gem/environment'" >&2
  exit 1
fi
